version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/travel_db
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - travel_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=travel_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d travel_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - travel_network

volumes:
  postgres_data:

networks:
  travel_network:
    driver: bridge
